language: node_js
node_js:
  # Latest stable version, Node 10 at the moment of creating config
  - 'lts/*'

cache:
  directories: node_modules/

# Blocklist
branches:
  except:
    # Will be deployed to, no need to build it
    - gh-pages

services:
  # Use docker to build h264bitstream for WASM
  - docker

before_install:
  - mkdir -p dist/
  - docker build -t h264bitstream-wasm .
  - docker create -ti --name h264bitstream-wasm-container h264bitstream-wasm
  - docker cp h264bitstream-wasm-container:/build/dist/ .
  - docker rm -fv h264bitstream-wasm-container

script:
  # Generates the dist folder with built app
  - npm run build
  # Runs tests
  - npm run test

# Deploys built application to gh-pages
# Git-ignored files won't be deployed.
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  # Directory to push to GitHub Pages, relative to the current directory
  local_dir: dist/
  # Prevent travis from cleaning out the branch before the deploy occurs
  skip_cleanup: true
  # Set in travis-ci.org dashboard in Environment Variables
  github_token: $GITHUB_TOKEN
  # Build only from master
  on:
    branch: master
